# Generated by Django 2.0.7 on 2019-06-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('treats', 'treate'), ('drinks', 'drinks'), ('entrees', 'entrees'), ('Appetizers', 'Appetizers')], max_length=60),
        ),
    ]
