# Generated by Django 2.0.7 on 2019-06-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190613_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('entrees', 'entrees'), ('drinks', 'drinks'), ('Appetizers', 'Appetizers'), ('treats', 'treats')], max_length=60),
        ),
    ]
